### ISSUE TITLE
User Story: Plan Checklist

### ISSUE THREAD

**Issue by tashiad** [Back-Country-Buddy/backcountry-buddy-UI#19]
As a user, I should be able to fill out the PLAN checklist for an upcoming tour. 
- [ ] Open an upcoming tour from the dashboard.
- [ ] I should see the four planning items for the checklist.
- [ ] Beneath each item I should be able to add details based sub-prompts.
- [ ] If I close and re-open this tour, my responses should be saved.
